services:

  epistudent:
    image: epistudent:latest
    container_name: epistudent-run
    build:
      dockerfile: Dockerfile
      context: ./StudentImage
    ports:
      - "8902:8900"
    volumes:
      - "${repo_dir}:/data/Epigenetics_Workshop/"
      - "${data_dir}:/data/Epigenetics_Workshop/input_data"
    restart: always

  epiteacher:
    image: epiteacher:latest
    container_name: epiteacher-run
    build:
      dockerfile: Dockerfile
      context: ./TeacherImage
    ports:
      - "8901:8900"
    entrypoint: "jupyterhub --ip 0.0.0.0 --port 8900 --config /root/.jupyter/jupyterhub_config.py"
    volumes:
      - "${repo_dir}:/data/Epigenetics_Workshop/"
      - "${data_dir}:/data/Epigenetics_Workshop/input_data"
    restart: always